# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j4primelte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/samsung/j2y18lte/proprietary/vendor/init/init.j2y18lte.rc:system/etc/init/init.j2y18lte.rc \
        vendor/samsung/j2y18lte/proprietary/vendor/vndk-sp-29/libcutils.so:system/lib/vndk-sp-29/libcutils.so \
        vendor/samsung/j2y18lte/proprietary/vendor/vndk-sp-29/libprocessgroup.so:system/lib/vndk-sp-29/libprocessgroup.so \
	vendor/samsung/j2y18lte/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so

